// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserServeice_Introduce_FullMethodName = "/user.UserServeice/Introduce"
)

// UserServeiceClient is the client API for UserServeice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServeiceClient interface {
	Introduce(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Result, error)
}

type userServeiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServeiceClient(cc grpc.ClientConnInterface) UserServeiceClient {
	return &userServeiceClient{cc}
}

func (c *userServeiceClient) Introduce(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, UserServeice_Introduce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServeiceServer is the server API for UserServeice service.
// All implementations should embed UnimplementedUserServeiceServer
// for forward compatibility
type UserServeiceServer interface {
	Introduce(context.Context, *UserInfo) (*Result, error)
}

// UnimplementedUserServeiceServer should be embedded to have forward compatible implementations.
type UnimplementedUserServeiceServer struct {
}

func (UnimplementedUserServeiceServer) Introduce(context.Context, *UserInfo) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Introduce not implemented")
}

// UnsafeUserServeiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServeiceServer will
// result in compilation errors.
type UnsafeUserServeiceServer interface {
	mustEmbedUnimplementedUserServeiceServer()
}

func RegisterUserServeiceServer(s grpc.ServiceRegistrar, srv UserServeiceServer) {
	s.RegisterService(&UserServeice_ServiceDesc, srv)
}

func _UserServeice_Introduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServeiceServer).Introduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServeice_Introduce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServeiceServer).Introduce(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServeice_ServiceDesc is the grpc.ServiceDesc for UserServeice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServeice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserServeice",
	HandlerType: (*UserServeiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Introduce",
			Handler:    _UserServeice_Introduce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
